/**
 * Client Gateway API
 * client gateway api
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Address } from './address';


export interface Customer { 
    /**
     *  customer id
     */
    id?: number;
    /**
     *  first name
     */
    first_name?: string;
    /**
     *  last or given name
     */
    last_name?: string;
    /**
     *  company name
     */
    company?: string;
    /**
     *  phone
     */
    phone?: string;
    /**
     *  email address
     */
    email?: string;
    /**
     *  is_verified
     */
    is_verified?: boolean;
    /**
     *  Address object
     */
    billing_addresses?: Array<Address>;
    /**
     *  array of Address objects
     */
    shipping_addresses?: Array<Address>;
}

