/**
 * Client Gateway API
 * client gateway api
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CustomerLoginRequest { 
    /**
     *  email address, unique to each store id
     */
    email: string;
    /**
     *  password
     */
    password: string;
}

