/**
 * Client Gateway API
 * client gateway api
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Item { 
    /**
     *  an item\'s variant sku number
     */
    note?: string;
    /**
     *  an item\'s variant sku number
     */
    sku?: string;
    /**
     *  how many of identical items
     */
    quantity?: number;
    /**
     *  the item\'s price
     */
    price?: number;
    /**
     *  when this item expires in the cart
     */
    expires_at?: string;
}

