/**
 * Client Gateway API
 * client gateway api
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { JwtToken } from './jwtToken';
import { Customer } from './customer';


export interface SetPasswordResponse { 
    jwt?: JwtToken;
    customer?: Customer;
    /**
     *  success bool
     */
    success: boolean;
}

