/**
 * Client Gateway API
 * client gateway api
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Address { 
    /**
     *  recipients name
     */
    recipient_name: string;
    /**
     *  street name, ie: 1723 NW 23rd Ave.
     */
    street: string;
    /**
     *  apartment or suite
     */
    apt_suite?: string;
    /**
     *  city name
     */
    city: string;
    /**
     *  state or province name
     */
    state_province: string;
    /**
     *  IISO 3166-1 alpha-2 country code. https:en.wikipedia.org/wiki/List_of_ISO_3166_country_codes
     */
    country: string;
    /**
     *  postal or zip code
     */
    postal_code: string;
    /**
     *  indicates if this is a commercial address
     */
    is_commercial: boolean;
    /**
     *  indicates if this is a default address
     */
    is_default: boolean;
}

