/**
 * Client Gateway API
 * client gateway api
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Item } from './item';
import { Address } from './address';


export interface Cart { 
    id?: string;
    store_id?: number;
    session?: string;
    customer_id?: number;
    first_name?: string;
    last_name?: string;
    company?: string;
    phone?: string;
    email?: string;
    billing_address?: Address;
    shipping_address?: Address;
    discount_id?: number;
    status?: Cart.StatusEnum;
    currency?: string;
    expires_at?: string;
    abandoned_at?: string;
    /**
     *  a collection of Item
     */
    items?: Array<Item>;
    /**
     *  the sum total of the cart
     */
    total_price: number;
}
export namespace Cart {
    export type StatusEnum = 0 | 1 | 2 | 3 | 4 | 5;
    export const StatusEnum = {
        NUMBER_0: 0 as StatusEnum,
        NUMBER_1: 1 as StatusEnum,
        NUMBER_2: 2 as StatusEnum,
        NUMBER_3: 3 as StatusEnum,
        NUMBER_4: 4 as StatusEnum,
        NUMBER_5: 5 as StatusEnum
    };
}


