/**
 * Client Gateway API
 * client gateway api
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Address } from './address';


export interface NewCustomer { 
    /**
     *  first name
     */
    first_name: string;
    /**
     *  last or given name
     */
    last_name: string;
    /**
     *  company name
     */
    company?: string;
    /**
     *  phone
     */
    phone?: string;
    /**
     *  email address, unique per store id
     */
    email: string;
    billing_address?: Address;
    shipping_address?: Address;
}

